/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'teleportProgress': MotiaStream<unknown>
  }

  interface Handlers {
    'SynthesizeSpeech': EventHandler<unknown, never>
    'GenerateLocationDetails': EventHandler<unknown, { topic: 'location-details-generated'; data: unknown } | { topic: 'synthesize-speech'; data: unknown }>
    'GenerateImage': EventHandler<unknown, { topic: 'image-generated'; data: unknown }>
    'CompleteTeleport': EventHandler<unknown, never>
    'ParseTravelCommand': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown>, never>
    'InitiateTeleport': ApiRouteHandler<unknown, ApiResponse<201, unknown> | ApiResponse<400, unknown>, { topic: 'generate-image'; data: unknown } | { topic: 'generate-location-details'; data: unknown }>
    'GetTeleportProgress': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'GetHistory': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'GetAudio': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
  }
}